repos:
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
        exclude: __init__.py

-   repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
    -   id: black
        args: [--preview]

-   repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
    -   id: flake8

- repo: local
  hooks:
    - id: pytest-check
      name: pytest-check
      stages: [push]
      types: [python]
      entry: pytest
      language: system
      pass_filenames: false
      always_run: true

- repo: https://github.com/DanielNoord/pydocstringformatter
  rev: v0.7.3
  hooks:
    - id: pydocstringformatter
      exclude: tests/.*
      args: [--max-line-length=88, --no-split-summary-body, --linewrap-full-docstring]
