[project]
name = "asyncfix"
version = "0.0.7"
description = "AsyncIO FIX Protocol client for Python"
readme = "README.md"
authors = [{ name = "Alex Veden", email = "i@alexveden.com" }]
license = {text = "MIT License"}
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.8",
    "Development Status :: 2 - Pre-Alpha",
]
keywords = ["async", "FIX", "protocol", "client", "server", "parser", "unit tests" ]
requires-python = ">=3.8"

dependencies = []

[project.optional-dependencies]
dev = [
  "pytest",
  "flake8==6.1.0",
  "black==23.7.0",
  "pre-commit",
  "Flake8-pyproject",
]

[project.urls]
Homepage = "https://github.com/alexveden/asyncfix"


[tool.isort]
profile = "black"

[tool.flake8]
extend-ignore = ['E203']
per-file-ignores = [
    './__init__.py:F401,F403',
    '**/__init__.py:F401,F403',
    '**/test_*.py:F405,E501,F841,F541,F403,F401,E741,W291,E265,W293',
]
max-line-length = 88
